### PR TITLE
Add support for target-content-id notification property

### PR DESCRIPTION
**Pull request by benagin**
See `target-content-id` [here](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2943361) and [here](https://developer.apple.com/documentation/usernotifications/unnotificationcontent/3235764-targetcontentidentifier).

### CODE REVIEW

**Review by cbaker6 — APPROVED** [review]

**Comment by cbaker6** [comment]
@davimacedo and this one?

**Comment by davimacedo** [comment]
@benagin would you mind to fix the conflicts?

**Comment by benagin** [comment]
Sure, fixed. Thanks for taking a look at this.

**Review by davimacedo — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
