### PR TITLE
Update node-forge and pin packages

### PR DESCRIPTION
**Pull request by davimacedo**

### CODE REVIEW

**Comment by davimacedo** [comment]
@funkenstrahlen do you have any idea on how to fix the tests?

**Comment by olleolleolle** [comment]
Failing test cases:

```
394 passing (697ms)
  2 failing

  1) Endpoint
       connect
         tls socket
           connection established
             writes the HTTP/2 prelude:

     AssertionError: expected write to have been called with arguments PRI * HTTP/2.0
      at Assertion.<anonymous> (node_modules/sinon-chai/lib/sinon-chai.js:105:18)
      at Assertion.ctx.(anonymous function) [as calledWith] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Context.<anonymous> (test/protocol/endpoint.js:138:56)

  2) Endpoint
       connect
         using an HTTP proxy
           tunnel established
             writes the HTTP/2 prelude:

     AssertionError: expected write to have been called with arguments PRI * HTTP/2.0
      at Assertion.<anonymous> (node_modules/sinon-chai/lib/sinon-chai.js:105:18)
      at Assertion.ctx.(anonymous function) [as calledWith] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Context.<anonymous> (test/protocol/endpoint.js:273:64)
```

What I have to go on: these function removals in node-forge:

[The `node-forge` 0.10.0 changelog](https://github.com/digitalbazaar/forge/blob/master/CHANGELOG.md#0100---2020-09-01)

**Review by dplewis — APPROVED** [review]
LGTM!

**Comment by olleolleolle** [comment]
@davidmacedo Thanks for the fix! Super!

**Pull request merged**
