### PR TITLE
fix: Incorrect field name `event` instead of `events` in Live Activity push notification payload

### PR DESCRIPTION
**Pull request by dplewis**
Per the documentation https://developer.apple.com/documentation/activitykit/updating-and-ending-your-live-activity-with-activitykit-push-notifications

`event` should be `events`

### CODE REVIEW

**Comment by dplewis** [comment]
@mtrezza This is ready for review

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.3](https://github.com/parse-community/node-apn/releases/tag/5.2.3)

**Comment by kurtguenther** [comment]
@dplewis @mtrezza  this change seems wrong from the documentation that I see on your [referenced page](https://developer.apple.com/documentation/activitykit/updating-live-activities-with-activitykit-push-notifications).

```
  "aps": {
        "timestamp": 1685952000,
        "event": "update",
        ...
```

It clearly says that we should use `event` and NOT `events`.

Using my own project, I am able to send live activity updates using version `5.2.2` but in `5.2.3` (which contains the event => events PR here) breaks pushing live activity updates. 

When I review the Console log I see this error `Incoming message does not contain an event type` which makes sense since iOS is looking for the `events` rather than `events` field.

Should we roll this back? Or am I way off course here.

Thanks,

**Comment by dplewis** [comment]
Apple must have updated the API. events type did look weird to me.

Can you open a new issue?

**Comment by kurtguenther** [comment]
Will do! I'm going to push up a PR that also includes the `dismissal-date` field which is used when a live activity is ended.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.2](https://github.com/parse-community/node-apn/releases/tag/6.0.2)

**Pull request merged**
