### PR TITLE
feat: Add support for Node 18, 20

### LINKED ISSUE #132: Add support for Node 18, 20

### PR DESCRIPTION
**Pull request by mtrezza**
Closes #132

Node 18, 20 tests are failing, needs further investigation.

### CODE REVIEW

**Comment by dplewis** [comment]
You can do something like this to fix the tests

https://github.com/dplewis/node-apn/commit/5acbe5991cff02649cfd8fa1aa18363f1e2970d9

**Comment by dplewis** [comment]
@mtrezza Did you see my feedback?

**Comment by mtrezza** [comment]
I leave it for someone to pick this up

**Comment by mtrezza** [comment]
Superseded by https://github.com/parse-community/node-apn/pull/137.

**Pull request closed without merging**
