### PR TITLE
fix(types): add proxy and fix logger

### PR DESCRIPTION
**Pull request by kinolaev**
Hello!
Tried to build my app with main branch but `tsc` warns about incorrect type declarations which are fixed in this PR.
I hope this PR will be included in the next release #70.

### CODE REVIEW

**Comment by kinolaev** [comment]
Rebased to v4.1.0 (72437e2cfb3e6974976db4dbb912d0768885b415)

**Review by davimacedo — APPROVED** [review]
LGTM!

**Comment by kinolaev** [comment]
Thank you @davimacedo, what about patch release?)

**Comment by davimacedo** [comment]
I've just created the PR: https://github.com/parse-community/node-apn/pull/74

**Pull request merged**
